export const FETCH_PROPERTY = "FETCH_PROPERTY";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY:SUCCESS";
export const FETCH_PROPERTY_ERROR = "FETCH_PROPERTY:ERROR";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS:SUCCESS";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS:ERROR";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT:SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT:ERROR";

export const HIDE_COMMENT_ERROR = "HIDE_COMMENT:ERROR";
