export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN:SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN:ERROR";

export const SIGN_IN_GOOGLE = "SIGN_IN_GOOGLE";
export const SIGN_IN_GOOGLE_SUCCESS = "SIGN_IN_GOOGLE:SUCCESS";
export const SIGN_IN_GOOGLE_ERROR = "SIGN_IN_GOOGLE:ERROR";

export const SIGN_IN_FORGOT = "SIGN_IN_FORGOT";
export const SIGN_IN_FORGOT_SUCCESS = "SIGN_IN_FORGOT:SUCCESS";
export const SIGN_IN_FORGOT_ERROR = "SIGN_IN_FORGOT:ERROR";

export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT:SUCCESS";
export const SIGN_OUT_ERROR = "SIGN_OUT:ERROR";

export const SIGN_UP_FIRST_STEP = "SIGN_UP_FIRST_STEP";
export const SIGN_UP_FIRST_STEP_SUCCESS = "SIGN_UP_FIRST_STEP:SUCCESS";
export const SIGN_UP_FIRST_STEP_ERROR = "SIGN_UP_FIRST_STEP:ERROR";

export const SIGN_UP_VERIFY = "SIGN_UP_VERIFY_STEP";
export const SIGN_UP_VERIFY_SUCCESS = "SIGN_UP_VERIFY:SUCCESS";
export const SIGN_UP_VERIFY_ERROR = "SIGN_UP_VERIFY:ERROR";

export const SIGN_UP_RESEND_CODE = "SIGN_UP_RESEND_CODE";
export const SIGN_UP_RESEND_CODE_SUCCESS = "SIGN_UP_RESEND_CODE:SUCCESS";
export const SIGN_UP_RESEND_CODE_ERROR = "SIGN_UP_RESEND_CODE:ERROR";



export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP:SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP:ERROR";

export const UPDATE_USER= "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER:SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER:ERROR";

export const HIDE_USER_ERROR = "HIDE_USER_ERROR";
export const SET_USER_ERROR =  "SET_USER_ERROR";
